#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "../../drivers/can/com/Com.h"

static uint8_t Test_Frame[8];
static uint32_t Test_FrameCount;

/** Capture the production KeepAlive I-PDU generated by COM. */
Std_ReturnType PduR_ComTransmit(PduIdType Id, const PduInfoType *InfoPtr)
{
    assert(Id == COM_IPDU_TX_KEEPALIVE);
    assert(InfoPtr != NULL && InfoPtr->SduLength == sizeof(Test_Frame));
    memcpy(Test_Frame, InfoPtr->SduDataPtr, sizeof(Test_Frame));
    Test_FrameCount++;
    return E_OK;
}

#include "../../drivers/can/com/Com.c"
#include "../../drivers/can/com/Com_Cfg.c"

/** Verify COM transmits `[AliveCounter][RateLevel][zero...]` with DLC 8. */
int main(void)
{
    uint32_t alive = 0xA5U;
    uint32_t level = 6U;
    uint8_t index;

    assert(Com_Init() == E_OK);
    assert(Com_SetTxIPduEnabled(COM_IPDU_TX_KEEPALIVE, 1U) == E_OK);
    assert(Com_SendSignal(COM_SIGNAL_TX_ALIVE_COUNTER, &alive) == E_OK);
    assert(Com_SendSignal(COM_SIGNAL_TX_KEEPALIVE_RATE, &level) == E_OK);
    Com_MainFunctionTx();
    assert(Test_FrameCount == 1U);
    assert(Test_Frame[0] == alive && Test_Frame[1] == level);
    for (index = 2U; index < sizeof(Test_Frame); index++)
    {
        assert(Test_Frame[index] == 0U);
    }
    puts("PASS: COM KeepAlive Tx frame has the required DLC8 layout.");
    return 0;
}
